@startuml HelpDesk_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Diagrama de Contexto (Nível 1) - Sistema de Notificação e Mensageria

Person(user, "Usuário cliente", "Abre tickets e recebe notificações")
Person(agent, "Agente / Técnico", "Atende e recebe notificações")
Person(admin, "Administrador", "Gerencia templates, reprocessa falhas")
System_Ext(emailProvider, "SES / SMTP", "Serviço de envio de e-mail")
System_Ext(pushProvider, "FCM / APNs", "Serviço de push")
System_Ext(auth, "Auth (Cognito / JWT)", "Autenticação")
System(system, "HelpDesk (Notificação e Mensageria)", "Sistema event-driven para notificações e mensageria. Veja docs. ")

Rel(user, system, "Cria ticket / visualiza logs (HTTP)")
Rel(agent, system, "Recebe notificações / usa Admin UI")
Rel(admin, system, "Administra reenvios")
Rel(system, emailProvider, "Envia e-mails via SES")
Rel(system, pushProvider, "Envia push via FCM/APNs")
Rel(system, auth, "Valida tokens / autenticação")

Note as N1
**Nível de detalhes:**
- Nenhum detalhe técnico específico.
- Não mostra APIs, tabelas ou filas.
- Apenas "pessoas ↔ sistema ↔ outros sistemas".
End note

Note as N2
**Amazon SES:**
O Amazon SES (Simple Email Service) é um serviço de nuvem da Amazon Web Services (AWS) que permite enviar e receber e-mails em grande volume de forma barata e escalável
End note

Note as N3
**FCM / APNs:**
O FCM (Firebase Cloud Messaging) e APNs (Apple Push Notification service) são serviços de notificação de push da Google e da Apple, respectivamente. Eles permitem enviar notificações de push para dispositivos móveis e desktops.
End note

Note as N4
**AWS Cognito:**
O AWS Cognito é um serviço de autenticação e gerenciamento de identidade da AWS que permite autenticar e gerenciar usuários e identidades em aplicações web e móveis.
End note

@enduml
