@startuml HelpDesk_Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Container (Nível 2) - Sistema de Notificação e Mensageria

Person(user, "Usuário", "Abre tickets e recebe notificações")

System_Boundary(system, "Notification System") {
  Container(UI, "UI", "React.js", "UI para usuários e administradores")
  Container(producer, "Producer API", "Spring Boot / Node.js", "Exposes REST endpoints and publishes events")
  Container(sqs, "Broker (SQS)", "AWS SQS", "Gerencia a fila de mensagens.")
  Container(notificationProcessor, "Notification Processor", "Node.js / TypeScript", "Serviço responsável por pollar a fila, processar eventos e enviar notificações.")
  Container(db, "Amazon RDS", "SQL", "Armazena modelos e registros de notificações.")
  Container(obs, "Observability", "CloudWatch / X-Ray", "Fornece registros, métricas e rastreamento.")
}
System_Ext(auth, "Auth (Cognito / JWT)", "Serviço de autenticação")

Rel(user, UI , "Visualiza e gerencia seus chamados.")
Rel(UI, producer, "Solicita informações por meio de chamados.", "JSON/HTTPS")
Rel(producer, sqs, "Publica eventos (SQS)")
Rel(sqs, notificationProcessor, "Aciona o processamento")
Rel(notificationProcessor, db, "Lê e escreve em modelos e registros")
Rel(notificationProcessor, obs, "Envia registros e métricas.")
Rel(producer, auth, "Valida tokens / autenticação")

@enduml
